keepEmptyPriority: false
code:
  include_lists:
    - TODO
    - DOING
    - DONE
    - PLANNING
    - FIXME
    - ARCHIVE
    - HACK
    - CHANGED
    - XXX
    - IDEA
    - NOTE
    - REVIEW
lists:
  - filter: 'due=lt=(${tomorrow at 6AM})&list=ne=DONE&sort(+due,+order)'
    hidden: true
    id: 0
    name: What's due?
  - hidden: true
    ignore: false
    name: NOTE
  - hidden: false
    name: TODO
  - hidden: false
    name: DOING
  - hidden: false
    name: DONE
settings:
  addNewCardsToTop: true
  appendNewCardsTo: todo-inbox.md
  cards:
    colors: []
  doneList: DONE
  filterHistory:
    - list=DONE
    - list-DONE
    - 'list:DONE'
  filteredLists:
    - filter: 'due=lt=(${tomorrow at 6AM})&list=ne=DONE&sort(+due,+order)'
      name: What's due?
  journalPath: null
  journalTemplate: |
    ---
    computed:
      date: (new Date()).toDateString()
      time: (new Date()).toLocaleTimeString()
      timestamp: (new Date()).toISOString()
    template: | # This is the template for new cards that are created in imdone
      
      <!-- created:${timestamp} -->
      <!--[ Created: {{(new Date(created)).toLocaleString()}} ]-->
    links:
      - pack: fab # Can be fab or fas https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use
        icon: fa-twitter # The font-awesome icon to use
        title: Tweet this card
        href: https://twitter.com/intent/tweet?text=${encodedText}%0ATweeted%20with%20@imdoneio
    ---
  journalType: Single File
  maxLines: 6
  newCardSyntax: HASHTAG
  replaceSpacesWith: '-'
  taskPrefix: ''
